### ISSUE TITLE
Import YAML error on netobs 

### ISSUE THREAD

**Issue by dblanco940** [network-observability/network-observability-lab#14]
In the last stage of creating a droplet in Digital Ocean, there is an error where the droplet can't import the yaml module. 

Logs shown below:

```
digitalocean_droplet.netobs_vm (remote-exec): Traceback (most recent call last):
digitalocean_droplet.netobs_vm (remote-exec):   File "/root/miniconda/bin/netobs", line 5, in <module>
digitalocean_droplet.netobs_vm (remote-exec):     from netobs.main import app
digitalocean_droplet.netobs_vm (remote-exec):   File "/root/miniconda/lib/python3.11/site-packages/netobs/main.py", line 14, in <module>
digitalocean_droplet.netobs_vm (remote-exec):     import yaml
digitalocean_droplet.netobs_vm (remote-exec): ModuleNotFoundError: No module named 'yaml'
╷
│ Error: remote-exec provisioner error
│
│   with digitalocean_droplet.netobs_vm,
│   on servers.tf line 88, in resource "digitalocean_droplet" "netobs_vm":
│   88:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1206405785.sh": Process exited with status 1
```

**Comment by davidban77** [comment]
This is now fixed with the new deployment Ansible method
