### ISSUE TITLE
Docker cannot run in DO VM

### ISSUE THREAD

**Issue by davidban77** [network-observability/network-observability-lab#5]
There are issues running docker with the current provisioning scripts:

```shell
root@netobs-chadell:~# docker
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

@[chadell](https://github.com/chadell)

I had to do a remove and install python3-apt
But the docker installation is not working well

```
    sudo apt remove python3-apt
    sudo apt install python3-apt
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

**Comment by davidban77** [comment]
This has been fixed with the docker installation script
